// Role hierarchy and permissions for School Management System
export const ROLES = {
  SUPER_ADMIN: "super_admin",
  PRINCIPAL: "principal",
  VICE_PRINCIPAL: "vice_principal",
  HOD: "hod",
  TEACHER: "teacher",
  STUDENT: "student",
  ACCOUNTANT: "accountant",
  GUARD: "guard",
  CLEANER: "cleaner",
  HR: "hr",
  FOUNDER: "founder",
  STAFF: "staff",
};

// Permission definitions
export const PERMISSIONS = {
  // Students
  VIEW_STUDENTS: "view_students",
  CREATE_STUDENTS: "create_students",
  EDIT_STUDENTS: "edit_students",
  DELETE_STUDENTS: "delete_students",

  // Teachers
  VIEW_TEACHERS: "view_teachers",
  CREATE_TEACHERS: "create_teachers",
  EDIT_TEACHERS: "edit_teachers",
  DELETE_TEACHERS: "delete_teachers",

  // Classes
  VIEW_CLASSES: "view_classes",
  CREATE_CLASSES: "create_classes",
  EDIT_CLASSES: "edit_classes",
  DELETE_CLASSES: "delete_classes",

  // Class Subjects
  VIEW_CLASS_SUBJECTS: "view_class_subjects",
  MANAGE_CLASS_SUBJECTS: "manage_class_subjects",

  // Attendance
  VIEW_ATTENDANCE: "view_attendance",
  MARK_ATTENDANCE: "mark_attendance",

  // Exams
  VIEW_EXAMS: "view_exams",
  CREATE_EXAMS: "create_exams",
  EDIT_EXAMS: "edit_exams",
  DELETE_EXAMS: "delete_exams",
  ENTER_RESULTS: "enter_results",

  // Assignments
  VIEW_ASSIGNMENTS: "view_assignments",
  CREATE_ASSIGNMENTS: "create_assignments",
  SUBMIT_ASSIGNMENTS: "submit_assignments",

  // Fees
  VIEW_FEES: "view_fees",
  MANAGE_FEES: "manage_fees",

  // Events
  CREATE_EVENTS: "create_events",
  VIEW_EVENTS: "view_events",
  EDIT_EVENTS: "edit_events",
  DELETE_EVENTS: "delete_events",

  // Announcements
  CREATE_ANNOUNCEMENTS: "create_announcements",
  VIEW_ANNOUNCEMENTS: "view_announcements",
  EDIT_ANNOUNCEMENTS: "edit_announcements",
  DELETE_ANNOUNCEMENTS: "delete_announcements",

  // Messages
  SEND_MESSAGES: "send_messages",
  VIEW_MESSAGES: "view_messages",

  // Schedules
  VIEW_SCHEDULE: "view_schedule",
  MANAGE_SCHEDULE: "manage_schedule",

  // Payroll
  VIEW_PAYROLL: "view_payroll",
  MANAGE_PAYROLL: "manage_payroll",

  // Admissions
  VIEW_ADMISSIONS: "view_admissions",
  MANAGE_ADMISSIONS: "manage_admissions",

  // Blogs
  VIEW_BLOGS: "view_blogs",
  MANAGE_BLOGS: "manage_blogs",

  // Leaves
  VIEW_LEAVES: "view_leaves",
  MANAGE_LEAVES: "manage_leaves",
  SUBMIT_LEAVE: "submit_leave",

  // Library
  VIEW_LIBRARY: "view_library",
  MANAGE_LIBRARY: "manage_library",

  // Visitors
  VIEW_VISITORS: "view_visitors",
  MANAGE_VISITORS: "manage_visitors",
};

// Role-Permission mapping
export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: [...Object.values(PERMISSIONS)],

  [ROLES.PRINCIPAL]: [
    PERMISSIONS.VIEW_STUDENTS,
    PERMISSIONS.CREATE_STUDENTS,
    PERMISSIONS.EDIT_STUDENTS,
    PERMISSIONS.DELETE_STUDENTS,
    PERMISSIONS.VIEW_TEACHERS,
    PERMISSIONS.CREATE_TEACHERS,
    PERMISSIONS.EDIT_TEACHERS,
    PERMISSIONS.DELETE_TEACHERS,
    PERMISSIONS.VIEW_CLASSES,
    PERMISSIONS.CREATE_CLASSES,
    PERMISSIONS.EDIT_CLASSES,
    PERMISSIONS.DELETE_CLASSES,
    PERMISSIONS.VIEW_CLASS_SUBJECTS,
    PERMISSIONS.MANAGE_CLASS_SUBJECTS,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.VIEW_EXAMS,
    PERMISSIONS.CREATE_EXAMS,
    PERMISSIONS.EDIT_EXAMS,
    PERMISSIONS.ENTER_RESULTS,
    PERMISSIONS.VIEW_ASSIGNMENTS,
    PERMISSIONS.CREATE_ASSIGNMENTS,
    PERMISSIONS.VIEW_FEES,
    PERMISSIONS.MANAGE_FEES,
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.CREATE_EVENTS,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    PERMISSIONS.CREATE_ANNOUNCEMENTS,
    PERMISSIONS.SEND_MESSAGES,
    PERMISSIONS.VIEW_MESSAGES,
    PERMISSIONS.VIEW_SCHEDULE,
    PERMISSIONS.MANAGE_SCHEDULE,
    PERMISSIONS.VIEW_PAYROLL,
    PERMISSIONS.MANAGE_PAYROLL,
    PERMISSIONS.VIEW_ADMISSIONS,
    PERMISSIONS.MANAGE_ADMISSIONS,
    PERMISSIONS.VIEW_BLOGS,
    PERMISSIONS.MANAGE_BLOGS,
    PERMISSIONS.VIEW_LEAVES,
    PERMISSIONS.MANAGE_LEAVES,
    PERMISSIONS.VIEW_LIBRARY,
    PERMISSIONS.MANAGE_LIBRARY,
    PERMISSIONS.VIEW_VISITORS,
    PERMISSIONS.MANAGE_VISITORS,
  ],

  [ROLES.VICE_PRINCIPAL]: [
    PERMISSIONS.VIEW_STUDENTS,
    PERMISSIONS.EDIT_STUDENTS,
    PERMISSIONS.VIEW_TEACHERS,
    PERMISSIONS.VIEW_CLASSES,
    PERMISSIONS.EDIT_CLASSES,
    PERMISSIONS.VIEW_CLASS_SUBJECTS,
    PERMISSIONS.MANAGE_CLASS_SUBJECTS,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.VIEW_EXAMS,
    PERMISSIONS.CREATE_EXAMS,
    PERMISSIONS.ENTER_RESULTS,
    PERMISSIONS.VIEW_ASSIGNMENTS,
    PERMISSIONS.CREATE_ASSIGNMENTS,
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.CREATE_EVENTS,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    PERMISSIONS.CREATE_ANNOUNCEMENTS,
    PERMISSIONS.SEND_MESSAGES,
    PERMISSIONS.VIEW_MESSAGES,
    PERMISSIONS.VIEW_SCHEDULE,
    PERMISSIONS.MANAGE_SCHEDULE,
    PERMISSIONS.VIEW_PAYROLL,
    PERMISSIONS.MANAGE_PAYROLL,
    PERMISSIONS.VIEW_ADMISSIONS,
    PERMISSIONS.MANAGE_ADMISSIONS,
    PERMISSIONS.VIEW_LEAVES,
    PERMISSIONS.VIEW_LIBRARY,
    PERMISSIONS.MANAGE_LIBRARY,
    PERMISSIONS.VIEW_VISITORS,
    PERMISSIONS.MANAGE_VISITORS,
  ],

  [ROLES.HOD]: [
    PERMISSIONS.VIEW_STUDENTS,
    PERMISSIONS.VIEW_TEACHERS,
    PERMISSIONS.VIEW_CLASSES,
    PERMISSIONS.VIEW_CLASS_SUBJECTS,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.MARK_ATTENDANCE,
    PERMISSIONS.VIEW_EXAMS,
    PERMISSIONS.CREATE_EXAMS,
    PERMISSIONS.ENTER_RESULTS,
    PERMISSIONS.VIEW_ASSIGNMENTS,
    PERMISSIONS.CREATE_ASSIGNMENTS,
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    PERMISSIONS.SEND_MESSAGES,
    PERMISSIONS.VIEW_MESSAGES,
    PERMISSIONS.VIEW_SCHEDULE,
    PERMISSIONS.VIEW_PAYROLL,
    PERMISSIONS.VIEW_ADMISSIONS,
    PERMISSIONS.VIEW_BLOGS,
    PERMISSIONS.SUBMIT_LEAVE,
    PERMISSIONS.VIEW_LIBRARY,
  ],

  [ROLES.TEACHER]: [
    PERMISSIONS.VIEW_BLOGS,
    PERMISSIONS.MANAGE_BLOGS,
    PERMISSIONS.VIEW_STUDENTS,
    PERMISSIONS.VIEW_CLASSES,
    PERMISSIONS.VIEW_CLASS_SUBJECTS,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.MARK_ATTENDANCE,
    PERMISSIONS.VIEW_EXAMS,
    PERMISSIONS.CREATE_EXAMS,
    PERMISSIONS.ENTER_RESULTS,
    PERMISSIONS.VIEW_ASSIGNMENTS,
    PERMISSIONS.CREATE_ASSIGNMENTS,
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    PERMISSIONS.SEND_MESSAGES,
    PERMISSIONS.VIEW_MESSAGES,
    PERMISSIONS.VIEW_SCHEDULE,
    PERMISSIONS.VIEW_PAYROLL,
    PERMISSIONS.SUBMIT_LEAVE,
    PERMISSIONS.VIEW_LIBRARY,
  ],

  [ROLES.STUDENT]: [
    PERMISSIONS.VIEW_CLASSES,
    PERMISSIONS.VIEW_CLASS_SUBJECTS,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.VIEW_EXAMS,
    PERMISSIONS.VIEW_ASSIGNMENTS,
    PERMISSIONS.SUBMIT_ASSIGNMENTS,
    PERMISSIONS.VIEW_FEES,
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    PERMISSIONS.SEND_MESSAGES,
    PERMISSIONS.VIEW_MESSAGES,
    PERMISSIONS.VIEW_SCHEDULE,
    PERMISSIONS.VIEW_BLOGS,
    PERMISSIONS.SUBMIT_LEAVE,
    PERMISSIONS.VIEW_LIBRARY,
  ],

  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.VIEW_STUDENTS,
    PERMISSIONS.VIEW_FEES,
    PERMISSIONS.MANAGE_FEES,
    PERMISSIONS.SEND_MESSAGES,
    PERMISSIONS.VIEW_MESSAGES,
    PERMISSIONS.VIEW_PAYROLL,
    PERMISSIONS.MANAGE_PAYROLL,
    PERMISSIONS.SUBMIT_LEAVE,
  ],

  [ROLES.GUARD]: [
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    PERMISSIONS.VIEW_PAYROLL,
    PERMISSIONS.SUBMIT_LEAVE,
    PERMISSIONS.VIEW_VISITORS,
    PERMISSIONS.MANAGE_VISITORS,
  ],

  [ROLES.CLEANER]: [
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    PERMISSIONS.VIEW_PAYROLL,
    PERMISSIONS.SUBMIT_LEAVE,
  ],
  [ROLES.HR]: [
    PERMISSIONS.VIEW_STUDENTS,
    PERMISSIONS.VIEW_TEACHERS,
    PERMISSIONS.CREATE_TEACHERS,
    PERMISSIONS.EDIT_TEACHERS,
    PERMISSIONS.DELETE_TEACHERS,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.VIEW_PAYROLL,
    PERMISSIONS.MANAGE_PAYROLL,
    PERMISSIONS.VIEW_LEAVES,
    PERMISSIONS.MANAGE_LEAVES,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    PERMISSIONS.CREATE_ANNOUNCEMENTS,
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.CREATE_EVENTS,
    PERMISSIONS.VIEW_MESSAGES,
    PERMISSIONS.SEND_MESSAGES,
  ],

  [ROLES.FOUNDER]: [...Object.values(PERMISSIONS)],

  [ROLES.STAFF]: [
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.VIEW_PAYROLL,
    PERMISSIONS.SUBMIT_LEAVE,
    PERMISSIONS.VIEW_MESSAGES,
    PERMISSIONS.SEND_MESSAGES,
  ],
};

// Utility functions (unchanged)
export const hasPermission = (userRole, permission) => {
  if (!userRole || !permission) return false;
  const rolePermissions = ROLE_PERMISSIONS[userRole] || [];
  return rolePermissions.includes(permission);
};

export const hasAnyPermission = (userRole, permissions = []) => {
  return permissions.some((permission) => hasPermission(userRole, permission));
};

export const hasAllPermissions = (userRole, permissions = []) => {
  return permissions.every((permission) => hasPermission(userRole, permission));
};

export const getRolePermissions = (role) => {
  return ROLE_PERMISSIONS[role] || [];
};
